apiVersion: v1
kind: ConfigMap
metadata:
  name: wigglenet-config
  namespace: kube-system
data:
  MASQUERADE_IPV4: "true"
  MASQUERADE_IPV6: "true"
  FILTER_IPV4: "false"
  FILTER_IPV6: "false" 
  NODE_IP_INTERFACE: ""
  NODE_IP_FAMILY: ""
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: wigglenet
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - list
      - watch
      - update
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: wigglenet
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: wigglenet
subjects:
- kind: ServiceAccount
  name: wigglenet
  namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: wigglenet
  namespace: kube-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: wigglenet
  namespace: kube-system
  labels:
    tier: node
    app: wigglenet
    k8s-app: wigglenet
spec:
  selector:
    matchLabels:
      app: wigglenet
  template:
    metadata:
      labels:
        tier: node
        app: wigglenet
        k8s-app: wigglenet
    spec:
      hostNetwork: true
      tolerations:
      - operator: Exists
      serviceAccountName: wigglenet
      containers:
      - name: wigglenet-cni
        image: wigglenet
        imagePullPolicy: Never
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        envFrom:
        - configMapRef:
            name: wigglenet-config
        volumeMounts:
        - name: cfg
          mountPath: /etc/wigglenet
        - name: cni-cfg
          mountPath: /etc/cni/net.d
        - name: xtables-lock
          mountPath: /run/xtables.lock
          readOnly: false
        - name: lib-modules
          mountPath: /lib/modules
          readOnly: true
        resources:
          requests:
            cpu: "100m"
            memory: "50Mi"
          limits:
            cpu: "100m"
            memory: "50Mi"
        securityContext:
          privileged: false
          capabilities:
            add: ["NET_RAW", "NET_ADMIN"]
      volumes:
      - name: cfg
        hostPath:
          path: /etc/wigglenet
      - name: cni-cfg
        hostPath:
          path: /etc/cni/net.d
      - name: xtables-lock
        hostPath:
          path: /run/xtables.lock
          type: FileOrCreate
      - name: lib-modules
        hostPath:
          path: /lib/modules